[font]
size = 9
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic"}

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]

[scrolling]
history               = 65535
