#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if xrandr | grep "DP-5 connected" && xrandr | grep "DP-2 connected"; then
    # Dual monitor setup
    #xrandr --output DP-5 --auto --output DP-2 --auto --right-of HDMI1
    xrandr --output DP-2 --mode 1440x900 --rate 74.98
    xrandr --output DP-5 --mode 1440x900 --rate 74.98
    # Set workspaces for each monitor
    bspc monitor DP-5 -d I II III IV V
    bspc monitor DP-2 -d VI VII VIII IX X
    # Launch Polybar on both monitors
    polybar mybar &
    polybar mybar_two &
else
    # Single monitor setup
    xrandr --output HDMI-0 --auto --output DP1 --off
    bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

    # Launch Polybar only on the main monitor
    MONITOR=HDMI-0 polybar mybarLarge &
fi


bspc config border_width         3
bspc config window_gap           2
bspc config top_padding          6
bspc config right_padding        0
bspc config bottom_padding       0
bspc config left_padding         0

bspc config focused_border_color \#7AA2F7
bspc config active_border_color \#16161E
bspc config normal_border_color \#16161E

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  5
bspc config right_monocle_padding 0
bspc config bottom_monocle_padding -3
bspc config left_monocle_padding 0

bspc rule -a mpv state=floating
bspc rule -a Bitwarden state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Get rid of X cursor
xsetroot -cursor_name left_ptr

# autostart applications
picom --config $HOME/.config/picom/picom.conf &
dunst &
#polybar mybar &
#polybar mybar_two &
nitrogen --restore &
