#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-5 -d I II III IV V 
bspc monitor DP-2 -d VI VII VIII IX X

bspc config border_width         3
#bspc config window_gap           5
# bspc config top_padding          18
bspc config right_padding        6
bspc config bottom_padding       2
bspc config left_padding         6

bspc config focused_border_color \#7AA2F7
bspc config active_border_color \#16161E
bspc config normal_border_color \#16161E

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  5
bspc config right_monocle_padding -6
bspc config bottom_monocle_padding -6
bspc config left_monocle_padding -6

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Bitwarden state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Get rid of X cursor
xsetroot -cursor_name left_ptr

# autostart applications
picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar mybar &
polybar mybar_two &
nitrogen --restore &
